name: sandpit-publish

on:
    workflow_dispatch:
        
jobs:
  pypi-publish:
    name: upload release to TestPyPI
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: test.pypi
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
    steps:
      # retrieve your distributions here
      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
      - name: Build a binary wheel and a source tarball
        run: python3 -m build . --wheel --sdist
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
            repository-url: https://test.pypi.org/legacy/
